// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Get Current User by token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get Current User by token.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/books": {
            "get": {
                "description": "Get a list of books.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Get all books.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Books"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Creating a new book.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Create New book.",
                "parameters": [
                    {
                        "description": "the body to create a new book",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.bookInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Books"
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "Get a book by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Get book.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "book id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Books"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Delete a book by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Delete one book.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "book id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Update book by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Update book.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "book id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "the body to update an book",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.bookInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Books"
                        }
                    }
                }
            }
        },
        "/dosen": {
            "get": {
                "description": "Get a list of dosen.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dosen"
                ],
                "summary": "Get all Dosen.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Dosen"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Creating a new dosen.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dosen"
                ],
                "summary": "Create New dosen.",
                "parameters": [
                    {
                        "description": "the body to create a new dosen",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.dosenInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Dosen"
                        }
                    }
                }
            }
        },
        "/dosen/{id}": {
            "get": {
                "description": "Get a dosen by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dosen"
                ],
                "summary": "Get dosen.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dosen id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Dosen"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Delete a dosen by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dosen"
                ],
                "summary": "Delete one dosen.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dosen id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Update dosen by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dosen"
                ],
                "summary": "Update dosen.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "dosen id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update an dosen",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.dosenInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Dosen"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah": {
            "get": {
                "description": "Get a list of jadwalKuliah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jadwal kuliah"
                ],
                "summary": "Get all jadwalKuliah.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.JadwalKuliah"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Creating a new jadwalKuliah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jadwal kuliah"
                ],
                "summary": "Create New jadwalKuliah.",
                "parameters": [
                    {
                        "description": "the body to create a new jadwalKuliah",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.jadwalKuliahInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.JadwalKuliah"
                        }
                    }
                }
            }
        },
        "/jadwal-kuliah/{id}": {
            "get": {
                "description": "Get a jadwalKuliah by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jadwal kuliah"
                ],
                "summary": "Get jadwalKuliah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jadwalKuliah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.JadwalKuliah"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Delete a jadwalKuliah by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jadwal kuliah"
                ],
                "summary": "Delete one jadwalKuliah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jadwalKuliah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Update jadwalKuliah by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jadwal kuliah"
                ],
                "summary": "Update jadwalKuliah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "jadwalKuliah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update an jadwalKuliah",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.jadwalKuliahInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.JadwalKuliah"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Logging in to get jwt token to access admin or user api by roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login as as user.",
                "parameters": [
                    {
                        "description": "the body to login a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/mahasiswa": {
            "get": {
                "description": "Get a list of mahasiswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mahasiswa"
                ],
                "summary": "Get all Mahasiswa.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Mahasiswa"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Creating a new mahasiswa.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mahasiswa"
                ],
                "summary": "Create New mahasiswa.",
                "parameters": [
                    {
                        "description": "the body to create a new mahasiswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.mahasiswaInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Mahasiswa"
                        }
                    }
                }
            }
        },
        "/mahasiswa/{id}": {
            "get": {
                "description": "Get a mahasiswa by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mahasiswa"
                ],
                "summary": "Get mahasiswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mahasiswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Mahasiswa"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Delete a mahasiswa by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mahasiswa"
                ],
                "summary": "Delete one mahasiswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mahasiswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Update mahasiswa by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mahasiswa"
                ],
                "summary": "Update mahasiswa.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mahasiswa id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update an mahasiswa",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.mahasiswaInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Mahasiswa"
                        }
                    }
                }
            }
        },
        "/mata-kuliah": {
            "get": {
                "description": "Get a list of mataKuliah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mata kuliah"
                ],
                "summary": "Get all mataKuliah.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MataKuliah"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Creating a new mataKuliah.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mata kuliah"
                ],
                "summary": "Create New mataKuliah.",
                "parameters": [
                    {
                        "description": "the body to create a new mataKuliah",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.mataKuliahInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.MataKuliah"
                        }
                    }
                }
            }
        },
        "/mata-kuliah/{id}": {
            "get": {
                "description": "Get a mataKuliah by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mata kuliah"
                ],
                "summary": "Get mataKuliah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mataKuliah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MataKuliah"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Delete a mataKuliah by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mata kuliah"
                ],
                "summary": "Delete one mataKuliah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mataKuliah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Update mataKuliah by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mata kuliah"
                ],
                "summary": "Update mataKuliah.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "mataKuliah id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update an mataKuliah",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.mataKuliahInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MataKuliah"
                        }
                    }
                }
            }
        },
        "/nilai": {
            "get": {
                "description": "Get a list of nilai.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nilai"
                ],
                "summary": "Get all nilai.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Nilai"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Creating a new nilai.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nilai"
                ],
                "summary": "Create New nilai.",
                "parameters": [
                    {
                        "description": "the body to create a new nilai",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.nilaiInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Nilai"
                        }
                    }
                }
            }
        },
        "/nilai/{id}": {
            "get": {
                "description": "Get a nilai by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nilai"
                ],
                "summary": "Get nilai.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nilai id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Nilai"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Delete a nilai by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nilai"
                ],
                "summary": "Delete one nilai.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nilai id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerToken": []
                    }
                ],
                "description": "Update nilai by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nilai"
                ],
                "summary": "Update nilai.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nilai id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to update an nilai",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.nilaiInput"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Authorization. How to input in swagger : 'Bearer \u003cinsert_your_token_here\u003e'",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Nilai"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "registering a user from public access.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a user.",
                "parameters": [
                    {
                        "description": "the body to register a user",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.LoginInput": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.RegisterInput": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "controllers.bookInput": {
            "type": "object",
            "required": [
                "description",
                "image_url",
                "price",
                "release_year",
                "title",
                "total_page"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "release_year": {
                    "type": "integer",
                    "maximum": 2021,
                    "minimum": 1980
                },
                "title": {
                    "type": "string"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "controllers.dosenInput": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "mataKuliahID": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "controllers.jadwalKuliahInput": {
            "type": "object",
            "required": [
                "dosen_id",
                "hari",
                "jam_mulai",
                "jam_selesai",
                "mahasiswa_id"
            ],
            "properties": {
                "dosen_id": {
                    "type": "integer"
                },
                "hari": {
                    "type": "string"
                },
                "jam_mulai": {
                    "type": "string"
                },
                "jam_selesai": {
                    "type": "string"
                },
                "mahasiswa_id": {
                    "type": "integer"
                }
            }
        },
        "controllers.mahasiswaInput": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "controllers.mataKuliahInput": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string"
                }
            }
        },
        "controllers.nilaiInput": {
            "type": "object",
            "required": [
                "indeks",
                "mahasiswa_id",
                "mata_kuliah_id",
                "skor",
                "user_id"
            ],
            "properties": {
                "indeks": {
                    "type": "string"
                },
                "mahasiswa_id": {
                    "type": "integer"
                },
                "mata_kuliah_id": {
                    "type": "integer"
                },
                "skor": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Books": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                },
                "release_year": {
                    "type": "integer"
                },
                "thickness": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_page": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Dosen": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jadwalKuliah": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalKuliah"
                    }
                },
                "mataKuliahID": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.JadwalKuliah": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dosenID": {
                    "type": "integer"
                },
                "hari": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jam_mulai": {
                    "type": "string"
                },
                "jam_selesai": {
                    "type": "string"
                },
                "mahasiswaID": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Mahasiswa": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "jadwalKuliah": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.JadwalKuliah"
                    }
                },
                "nama": {
                    "type": "string"
                },
                "nilai": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Nilai"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.MataKuliah": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dosen": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Dosen"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "nilai": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Nilai"
                    }
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Nilai": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "indeks": {
                    "type": "string"
                },
                "mahasiswaID": {
                    "type": "integer"
                },
                "mataKuliahID": {
                    "type": "integer"
                },
                "skor": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
